a=np.array([[5,9,8],[4,11,6],[7,15,10]])
b=np.array([[0,-1,2],[4,6,10],[3,1,5]])
print("array of a : ")
print(a)
print("array of b : ")
print(b)
print("subtacting 2 from a : ")
print(a-2)
print("adding 3 with b : ")
print(b+3)
print("transposing b")
print(b.transpose())